# Generated by Django 3.0.3 on 2022-01-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
