# Generated by Django 3.0.3 on 2022-01-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='test',
        ),
    ]
